### ISSUE TITLE
[MD-380] GPS doesn't fix

### ISSUE THREAD

**Issue by sp5wwp** [OpenRTX/OpenRTX#104]
GPS doesn't fix even after 40 minutes under clear sky. Would be also cool if the firmware was able to detect if the radio has a GPS module in the first place :-)
Tested with a TYT MD-380 in both M17 and FM modes.

**Comment by silseva** [comment]
Your MD-380 with GPS is the one with the screen flipped, which is in our labs, so it was a false alarm.
GPS tested on RT3s, MD-390 and your MD-380 and works without problems.
