### ISSUE TITLE
MD390G: RX does not work

### ISSUE THREAD

**Issue by DC7IA** [OpenRTX/OpenRTX#11]
I can transmit on the MD390G, but receiving does not work.

Neither the LED goes on, nor do I hear any audio.

**Comment by DC7IA** [comment]
Since today, the microphone does not work anymore.

Yesterday I compiled and flashed the current code and it worked.
Today I pulled the changes and compiled and flashed again. Now I get a silent FM signal.

To make sure the microphone is not physically broken, I flashed back md380tools, which worked.

Looks like one of the commits today broke audio.

**Comment by silseva** [comment]
@n1zzo tested the fix in his MD390G and now everything works.
If you still have troubles, let me know!

**Comment by DC7IA** [comment]
RX still does not work.

**Comment by DC7IA** [comment]
My fault, had repeater shift on 😂
