### ISSUE TITLE
Possible problem on Accessibility menu

### ISSUE THREAD

**Issue by 7AAZ** [OpenRTX/OpenRTX#120]
Accessbility menu > Voice > OFF works well, Beep works well, when changed to level 1 rádio restart..
73s

https://user-images.githubusercontent.com/22869015/202575926-65a0a910-e0a9-459e-870a-4c4b87e1503b.mp4

**Comment by silseva** [comment]
Hi!
I tested the firmware on these radios, without issues:
- MD-380 UHF
- RT3 UHF
- MD-390 VHF

Unfortunately I don't have the exact same model of your radio...

You can try restore the settings to their default values and see what happens. Also, if you can please send a picture of the label in the battery slot, I can gather a bit more infos for the debugging.

Thanks!

**Comment by silseva** [comment]
Another question: the firmware image you have on the radio now is taken from the v0.3.5 release page (https://github.com/OpenRTX/OpenRTX/releases/tag/v0.3.5)?

**Comment by 7AAZ** [comment]
> Hi! I tested the firmware on these radios, without issues:
> 
> * MD-380 UHF
> * RT3 UHF
> * MD-390 VHF
> 
> Unfortunately I don't have the exact same model of your radio...
> 
> You can try restore the settings to their default values and see what happens. Also, if you can please send a picture of the label in the battery slot, I can gather a bit more infos for the debugging.
> 
> Thanks!

Hi,
Here goes the radio tag.
If you need anything else, I'm 100% available.

Hug !


![RT3](https://user-images.githubusercontent.com/22869015/202782305-758699c5-c439-481d-9574-83f9f8e8f25d.jpg)

**Comment by silseva** [comment]
Back on this after a bunch of time. What tool did you use to flash the firmware image into the radio? The TYT firmware update tool, `radio_tool` or the dmr.tools website?

**Comment by 7AAZ** [comment]
Welcome back :). I used the TYT firmware update tool, like other times before.
Available for whatever you need
Thaks
73s

**Comment by 7AAZ** [comment]
> Back on this after a bunch of time. What tool did you use to flash the firmware image into the radio? The TYT firmware update tool, `radio_tool` or the dmr.tools website?
/
Welcome back :). I used the TYT firmware update tool, like other times before.
Available for whatever you need
Thaks
73s

**Comment by silseva** [comment]
The bug seems to be related to the fact that the radio is flashed using the TYT firmware update tool.See https://github.com/OpenRTX/OpenRTX/issues/125

**Comment by silseva** [comment]
Bug reproduced on an MD-380 after flashing the firmware with the TYT upgrade tool. I'm closing this and publish the next updates on #125.
