### ISSUE TITLE
[mod17-ui] CAN can't be changed in the menu

### ISSUE THREAD

**Issue by sp5wwp** [OpenRTX/OpenRTX#123]
After entering the `Settings->M17 Settings` menu, CAN can't be changed nor set. Pressing the upper right button doesn't have any effect on the CAN menu entry.

**Comment by silseva** [comment]
Can you provide a video of the problem, please? In this way I can try fix it even without having a Module17 myself.

**Comment by sp5wwp** [comment]
OK, it can be set by using Left/Right buttons instead. Still, CAN and `Module17 Settings` appear to be volatile. They are not saved to flash.

**Comment by silseva** [comment]
Yes, because the changes are still in the `mod17-ui` branch. I was waiting to fix (or for the fix) this last problem before merging everything into master.

**Comment by silseva** [comment]
As from our discussion, we leave the value changeable with left/right buttons for consistency with the other settings entries.
