### ISSUE TITLE
Issues with MD-380 

### ISSUE THREAD

**Issue by silseva** [OpenRTX/OpenRTX#13]
On some versions of MD-380 targets we have:
- flipped screen
- RX not working
- TX working but with a ~20Hz noise superimposed to audio 

Affected devices having:
- SW version ≥ S13.032
- HW version ≥ 1704Axxxx

**Comment by sp5wwp** [comment]
TX works from 430.0000MHz to 438.8875MHz only. I didn't check lower frequencies.

**Comment by tarxvftech** [comment]
TX works at 451.8M, but not RX.

**Comment by tarxvftech** [comment]
For both devices:
MD380V (with GPS) with SN 160705088
MD380V (sans GPS) with SN 1507A15700

When flashed with 380 target, has a vertically mirrored display (but horizontally)
When flashed with 390 target, has a horizontally mirrored display (but vertically not mirrored)

**Comment by tarxvftech** [comment]
for flipped screens: https://github.com/travisgoodspeed/md380tools/issues/178
and the further linked issues at the bottom too

**Comment by silseva** [comment]
Thanks a lot!
I've encountered the issue on md380 tools and, also basing on this, we are planning to implement auto-detection of the display to have it correctly initialised on all the MDx devices.
We have found that original TYT firmware configures the display differently basing on a value stored in external flash's security register at address 0x301D: we are going to do the same on our firmware.

**Comment by sp5wwp** [comment]
"TX working but with a ~20Hz noise superimposed to audio"

It was not the MD380's fault. You can remove that.

**Comment by silseva** [comment]
Yep, thanks!
Recapping things, also basing on the new findings:
- flipped screen -> Confirmed, cause found (different display HW on each MD-380 HW revisions)
- RX not working -> Confirmed, cause found (will be solved when switching to RSSI-based squelch)

**Comment by sp5wwp** [comment]
I can transmit at 430.0000, 431.0000 and 433.0000 MHz but I'm unable to do it at 432.0000.

That's part II of https://github.com/OpenRTX/OpenRTX/issues/13#issuecomment-765460596

**Comment by sp5wwp** [comment]
It seems that transmitting at those frequencies results in a signal presence exactly 4.2 MHz below.

**Comment by silseva** [comment]
Hi everyone!
I'm working on the screen issues you reported by making the display driver auto-detecting the hardware configuration by reading the value of security register 0x301D.
However, I need your help to check if everything is working properly, since I only have an "old vocoder" MD-380: please compile and flash the firmware from the MDx-display branch (https://github.com/OpenRTX/OpenRTX/tree/MDx-display) and let me know if the display orientation is still broken.
The instructions for compilation and flashing can be found here: https://github.com/OpenRTX/OpenRTX/wiki/How-to-compile

Thanks and 73,
Silvano IU2KWO.

**Comment by tarxvftech** [comment]
@silseva : For my 3 single banders: your display branch works as expected on md380u, and on the MD380V and MD380VG is rotated 180 degrees (not mirrored, the display is upside down).

**Comment by n1zzo** [comment]
@tarxvftech can you test the latest release v0.2 again on your MD380s?

**Comment by tarxvftech** [comment]
(followed up on IRC, looks like a display issue on the VHF models, untested on the UHF model since it's display-less for the moment for other testing)

**Comment by silseva** [comment]
@tarxvftech can you please check if commit 984f840 fixed the issue?

**Comment by tarxvftech** [comment]
Will check in the next couple hours!

**Comment by tarxvftech** [comment]
@silseva MD380VG and MD380V are both upside down on current master (984f8409f4462b381662b19783cc1cbdb741c2b6) (e.g. rotated 180*)

**Comment by tarxvftech** [comment]
I'll poke around and see what I can do!

**Comment by tarxvftech** [comment]
Said it over discord, but 0xE0 for posterity :)

**Comment by silseva** [comment]
Updated to 0xE0 with commit 554c72c, thanks!
Now is everything fine.
