### ISSUE TITLE
Squelch level too low

### ISSUE THREAD

**Issue by F4FYF** [OpenRTX/OpenRTX#132]
Hi

I've just install OpenRTX Firmware on a RT3s with GPS.. Everything is allright but there is just the squelch level who is too low and open more often in analogique mode. Is there a tips to control it ?
Thanks for all

Jeff - F4FYF

**Comment by silseva** [comment]
Hi Jeff!
To adjust the squelch level you have to press the lowest side button to enter in the "macro" menu and then use either the channel selector knob or the arrows on the keypad to increase/decrease the level. Let me know if it worked!

Silvano IU2KWO

**Comment by F4FYF** [comment]
Hi Silvano

It's perfect ! everything works correctly and the squelch method is good. Thank you very much for everything.

Jeff - F4FYF

**Comment by silseva** [comment]
Nice, I'm happy for that! :D

73,
Silvano IU2KWO.
