### ISSUE TITLE
Module17 issues

### ISSUE THREAD

**Issue by sp5wwp** [OpenRTX/OpenRTX#138]
Here's the list (for the `mod17-ui` branch):
- volatile settings - TX/RX softpot values are rarely stored, I haven't yet figured out when. The rest of the settings under `Module17 Settings` are never stored
- CAN is only settable using left-right buttons, unlike other options. It is also not stored nor has any effect on the RF stream
- callsign entry is messed up - the entry field is being drawn on the menu (all items at the same time)
- `LAST` call isn't displayed

**Comment by silseva** [comment]
1) fixed
2) fixed too, for consistency I made all the numeric settings changeable only using left/right button
3) fixed
4) to be done

**Comment by silseva** [comment]
Displaying of last received callsign added with #185.
