### ISSUE TITLE
Need Debounce For MD-UV380 Mode Selection

### ISSUE THREAD

**Issue by robrobinette** [OpenRTX/OpenRTX#145]
About 30% of the time when I try to switch modes between M17 and FM Analog the radio switches to the new mode and immediately switches back to the old mode due to the lack of debounce. I'm running a daily from 15 July 23 in an MD-UV380 (with GPS).

**Comment by silseva** [comment]
Yes, is a bit annoying...
I'll fix it asap!

**Comment by silseva** [comment]
I consider this issue solved, then! :)
