### ISSUE TITLE
Add support for symbols

### ISSUE THREAD

**Issue by turnrye** [OpenRTX/OpenRTX#161]
# Motivation

To more efficiently communicate concepts in the UI, OpenRTX needs to be able to display symbols in addition to normal text.

## Requirements

- Support a variety of symbols, and make it easy to add new symbols in the future

## Choices

- Support SVGs

## References

The GFX package being used has a [good tutorial](https://learn.adafruit.com/creating-custom-symbol-font-for-adafruit-gfx-library/overview) on how to make new fonts.

**Comment by turnrye** [comment]
I've begun working on this in a branch.

**Comment by silseva** [comment]
Support for symbols is now in the master branch, thank you!
