### ISSUE TITLE
CI: Testing the code by building it

### ISSUE THREAD

**Issue by marcoSchr** [OpenRTX/OpenRTX#173]
It could be useful to test the code by compiling it for all targets.

# Current state

At the moment the firmware is only build when new code is pushed to master.

# Proposed Change

Build the firmware for all Pull requests

# Benefits

- We can see potential issues before a Pull request is merged
- We can see issues with specific targets because not everyone will test their changes with all targets

# Disadvantages

- Pull request pipelines will run longer
- More resources will be used for building the code every time

**Comment by silseva** [comment]
Works for me!

**Comment by silseva** [comment]
Implemented by PR #174, now merged in master.
