### ISSUE TITLE
M17 Spec Address Encoding Link

### ISSUE THREAD

**Issue by kc1awv** [OpenRTX/OpenRTX#178]
Please update the address encoding link on the CPS page to https://spec.m17project.org/ as the RTD instance is well out of date.

Since this link brings the viewer to the most recent PDF version of the specification, a reference to Appendix A should be added.

**Comment by sp5wwp** [comment]
Would be nice to place a line like `This appendix has been superseded by the OpenRTX CPS format.` in the M17 spec.

**Comment by silseva** [comment]
Link updated!
