### ISSUE TITLE
Feature: Show Volume on Screen

### ISSUE THREAD

**Issue by marcoSchr** [OpenRTX/OpenRTX#190]
It would be useful to show the current volume on screen.
This could be done in two ways.

1. Showing the Volume permanently on screen.
2. Show the Volume only when changing it.

**Comment by n1zzo** [comment]
This is particularly relevant for the T-TWR plus where no dial is present, thus there is no way to get the current volume level.

I would add another thin bar on top of the squelch one, personally I don’t fancy much the idea of a modal screen that takes away the attention from the main UI just to communicate a single number.

**Comment by marcoSchr** [comment]
This is an example of how it could look with a bar in the bottom.
First image is with a small screen, second image is with a large screen.

![screenshot_2023-11-05T11:26:34](https://github.com/OpenRTX/OpenRTX/assets/49691247/72e2e247-3bb0-4d82-acab-f3dc58f68c26)
![screenshot_2023-11-05T11:12:30](https://github.com/OpenRTX/OpenRTX/assets/49691247/4a654077-e063-46d0-89d4-fcfabf13e193)
