### ISSUE TITLE
Battery Calculation might underflow

### ISSUE THREAD

**Issue by marcoSchr** [OpenRTX/OpenRTX#192]
My RT3S turned off today when I tried to transmit and it would then no longer turn on.
I measured the battery voltage and got 0V.
After putting the battery into the charger for a few seconds, it returned with about 6.2V.
When I then turned on the device, I could see in the Info screen a voltage of 6.2V and the battery percentage showed 100%.
I investigated the battery calculation source code and found that it could underflow.

When the battery voltage is lower than the assumed minimum voltage, the calculation will underflow. [1]
This leads to the percentage calculation assuming the battery is 100%.  [2]

[[1] ](https://github.com/OpenRTX/OpenRTX/blob/master/openrtx/src/core/battery.c#L71)
[[2]](https://github.com/OpenRTX/OpenRTX/blob/master/openrtx/src/core/battery.c#L76)

**Comment by silseva** [comment]
Issue reproduced on linux emulator by setting the vbat to a value below the minimum.
