### ISSUE TITLE
Incorrect demodulation in UHF rx when bandwidth of 12.5 khz is used

### ISSUE THREAD

**Issue by andrealinux1** [OpenRTX/OpenRTX#21]
I flashed the latest `master` on my `uv390` (which is basically identical to the `uv380`).

The rx and tx capabilities are mostly fine, but I noticed an incorrect demodulation, causing voice not to be intelligible, when the radio is used on the UHF band, in rx mode.

Thanks to the help of @Nimayer, we noticed that this problem arises only when a bandwidth of 12.5 kHz is used, therefore happening mostly when you use pre-saved channels.
If you start up your radio in VFO mode, with a bandwidth of 20/25 kHz, the demodulation is correct and you can hear voice fine.

Let me know if I can help you with testing/reproducing the bug, and thanks again for this fantastic project!

**Comment by silseva** [comment]
Hi!
The bug should be fixed: if it is also for you, we can close the issue.

**Comment by andrealinux1** [comment]
> Hi!
> The bug should be fixed: if it is also for you, we can close the issue.

Thanks for looking into this, I will compile the master and check the issues ASAP, and report back here!

**Comment by andrealinux1** [comment]
Just tested, everything seems to work as expected! Mega Job!

**Comment by silseva** [comment]
Good!
Thanks to you for the testing!
