### ISSUE TITLE
module17 friendly LEDs

### ISSUE THREAD

**Issue by luzemario** [OpenRTX/OpenRTX#216]
LilyGo is selling several boards without displays. So there is the need to show basic status using board LEDs at boot, to give the user simple info about the board status.
Flashing sync LED quickly can do the trick, for example, as Arduino bootloader does.
Without display, the board appears to be dead everytime.

**Comment by silseva** [comment]
Hi!
Yes, is actually quite useful. I'll implement it in the next days.

**Comment by silseva** [comment]
Done! :)
