### ISSUE TITLE
Add an option to invert PTT logic on Module17

### ISSUE THREAD

**Issue by ManoDaSilva** [OpenRTX/OpenRTX#248]
Hey! In order to support the IC-F5060, we had to invert the logic in both PTT in and out by manually change the logic as it's active high... 

Is it possible to add an option on the Module17 config menu to invert that PTT logic?

**Comment by silseva** [comment]
Yes, I'll add this as soon as I have some time

**Comment by silseva** [comment]
Do you have suggestions for the name of the menu entry and the valued displayed?
I started with a "PTT level" entry label with "high" and "low" as possible values, but I'm not completely sure is understandable.

**Comment by ManoDaSilva** [comment]
Perhaps "PTT Logic In" and "PTT Logic Out" labels, if there's enough space?

**Comment by silseva** [comment]
I'd go for "PTT in" and "PTT out" la else, with "Act Hi" and "Act Lo" as values.

**Comment by silseva** [comment]
Done!
