### ISSUE TITLE
Frequency display issue - TYT MD-380

### ISSUE THREAD

**Issue by sp5wwp** [OpenRTX/OpenRTX#255]
When I punch in 435.05MHz, the radio displays it properly, but after I confirm that setting with the green button, the displayed frequency is 435.5. The radio transmits on the right frequency, it's just the displayed value that's wrong.

Tested on a TYT MD-380 running 0.3.6-93 and -99. Both are affected.

**Comment by sp5wwp** [comment]
BTW - bring back the trailing zeros, please :)

**Comment by silseva** [comment]
Is only a formatting problem, not a functional issue. The VCO frequency is correct.
