### ISSUE TITLE
MD-390G Frozen M17 freq entry

### ISSUE THREAD

**Issue by KC5CQW** [OpenRTX/OpenRTX#263]
I have a newly (today) modded MD-390G UHF that locks up when entering a frequency in M17 mode. Specifically, my hotspot at 432.55MHz. FM has good RX/TX into a local repeater. I nuked my HS bootloader so it isn't working right now to test DMR/M17 further.

**Comment by silseva** [comment]
Which firmware image did you flash? And with which tool?
In the past we found out that some of the TYT firmware update tools seem not to write the entire firmware image in the MCU flash, and this causes lockups/crashes.

**Comment by KC5CQW** [comment]
Good info, I used an old TYT program. I didn’t know of any alternatives. 73, DamonOn Apr 13, 2024, at 06:02, silseva ***@***.***> wrote:﻿
Which firmware image did you flash? And with which tool?
In the past we found out that some of the TYT firmware update tools seem not to write the entire firmware image in the MCU flash, and this causes lockups/crashes.

**Comment by silseva** [comment]
I need to update the README and the flashing instructions.
Let me know if you solved! :)

**Comment by silseva** [comment]
I assume you solved the problem, if not feel free to reopen the issue.
