### ISSUE TITLE
RTX not updated when switching from MEM to VCO mode

### ISSUE THREAD

**Issue by silseva** [OpenRTX/OpenRTX#30]
When switching back from MEM to VFO mode the RTX configuration is not updated to the last VCO state until either the frequency or any other setting  involving the RTX part is changed.
This can be easily spotted on linux emulator: when switching from MEM to VFO the `radio_updateConfiguration` function is never called, even if it should be.

**Comment by Nimayer** [comment]
Fixed with commit 68bcee0
