### ISSUE TITLE
DMR

### ISSUE THREAD

**Issue by NeleBrt** [OpenRTX/OpenRTX#33]
Hello,
Will you add DMR mode to OpenRTX, and when?

**Comment by n1zzo** [comment]
Hi @NeleBrt,
DMR support requires a working AMBE+2 codec, and that is presently patented, therefore we cannot implement the DMR functionality without a commercial agreement with DVSI, that holds the commercial rights of the patent.
Until the legal issues relative to the AMBE codec will be solved we will focus on free protocols such as [M17](https://m17project.org/).

**Comment by majkrzak** [comment]
No properitary code have to be used, as there seems to be some opensource implementations which can be utilised here. In the worst case, some effort to implement it by ourselves can be taken.
