### ISSUE TITLE
Create a button to open the squelch (at least in FM mode)

### ISSUE THREAD

**Issue by acfnews** [OpenRTX/OpenRTX#35]
Could a button (or a switchable parameter in the menu) be created for opening the squelch?
This would be nice to have in FM mode, and maybe also in digital modes to verify if a signal can be heard which is below the squelch detector.

On MD380 there is a 3rd button above the PTT which could be used for this, maybe it can be (user) programmed to do so?

**Comment by Tyler-2** [comment]
I too miss my "monitor" button.
