### ISSUE TITLE
Initial carrier offset when transmitting M17 after boot

### ISSUE THREAD

**Issue by Nimayer** [OpenRTX/OpenRTX#40]
When transmitting M17 for the first time after boot, a negative offset can be noticed on the carrier.
The carrier starts at the equivalent of -3 symbol and slowly fades away, leaving only regular M17 signal.

The offset appears only once after boot, it does not appears on later M17 transmissions.

**Comment by sp5wwp** [comment]
A simple workaround is to press and hold the PTT for about 4 seconds after switching to M17 mode for the first time after powering up the radio.

**Comment by sp5wwp** [comment]
Update: after the carrier is gone, for about 5 more seconds, the transmission is erroneous with periods of carrier-only. See attached scope screenshot (FM demod out from a receiver).

![DS0001](https://user-images.githubusercontent.com/44336093/141650921-b6390e6a-12d9-498e-969e-371af51dccf8.PNG)

**Comment by nolith** [comment]
As reported on Discord, the initial fading is present also on FM.

I'll try to test this on a stock RT3 (original FW and no modifications) to see if it's and hardware problem.

**Comment by nolith** [comment]
I did the test.

This is an RT3 running MD380Tools

https://user-images.githubusercontent.com/78752/142636439-db10d64b-469c-4de3-a3e1-36cc9ae1f61b.mov


And this is OpenRTX 0.3.2

https://user-images.githubusercontent.com/78752/142636657-b5aafcb2-d2fc-46b1-a08f-84f49e1ab419.mov

In both cases the signal was generated by a tune tone from WJST-X, but with openrtx we can see the carrier only signal for a longer period than what we see with the other firmware.


I think this is software bug and not an hardware problem

**Comment by nolith** [comment]
![Screen Shot 2021-12-01 at 22 53 56](https://user-images.githubusercontent.com/78752/144320600-5f89a55f-3080-483b-b3c0-86b29fc73fae.png)

It is not just after the first boot, every time the radio switches from FM to M17, the first signal has a period of carrier only

**Comment by silseva** [comment]
Problem solved by PR #93.
