### ISSUE TITLE
MD380: radio does not transmit with the external PTT signal

### ISSUE THREAD

**Issue by nolith** [OpenRTX/OpenRTX#52]
While recording the videos on https://github.com/OpenRTX/OpenRTX/issues/40#issuecomment-974110862 I realized than once I flashed the radio with OpenRTX it was no longer transmitting with the external PPT signal. As can be see in the second video, I had to pick the radio in my hand and press the PTT on the radio body.

**The radio is a Retevis RT3 UHF**

**Comment by nolith** [comment]
I did a second test with another PTT button.

It works with the stock fw
![original](https://user-images.githubusercontent.com/78752/142687079-a128530d-6c21-4e8b-9767-dc5106abb4ee.jpg)

But not with OpenRTX


![openrtx](https://user-images.githubusercontent.com/78752/142687134-7c55e893-63a9-451a-b92b-9953b42307fe.jpg)

**Comment by nolith** [comment]
As @silseva pointed out on Discord, there is no pull-up resistor on the RT3 and the internal one has to be enabled on the gpio port like in an MD-UV380

**Comment by silseva** [comment]
Fixed with commit dccefd0
