### ISSUE TITLE
TYT MD-UV390 can only monitor single channel?

### ISSUE THREAD

**Issue by Tyler-2** [OpenRTX/OpenRTX#66]
I didn't see this in the capability notes, and I didn't see that there was a way to restore this functionality in the user docs... But is it accurate that OpenRDX right now doesn't work to monitor multiple channels? I'm sorry i don't know the name for this... but in the original firmware you had two "slots" that could independently be channels/frequencies, and you could switch between them and tune them individually. You could for instance have two repeaters in those slots, so that if there were any transmissions from either repeater you'd hear it. It's what the up/down arrows are for on the main screen, switching between those two channels.

**Comment by silseva** [comment]
Hi!
You're right, we did not implement the dual watch functionality yet. We'll add it in the next updates, we're planning to restructure and update a significant part of the codebase.

**Comment by Tyler-2** [comment]
Was this closed because it was added in recent updates? If so, exciting!

**Comment by silseva** [comment]
Not yet, I'm sorry. In any case is recorded in our internal todo list as a feature to be added after the codebase reorganisation, which is going to start soon! ;)
