### ISSUE TITLE
RT3S incorrect voltage

### ISSUE THREAD

**Issue by kmihaylov** [OpenRTX/OpenRTX#72]
My battery indicator is (almost) fully green. Settings->Info gives 85%. Voltage is 6.9 to 6.10 (something wrong here...?).
However I checked the battery terminals w/ the multimeter and the voltage is 7.16V. How does the firmware checks the voltage?

**Comment by silseva** [comment]
Hi!
Voltage is measured using an ADC channel connected to a voltage divider directly connected to the battery.
I did a quick test now on my MD380: the battery is at 7.44V and the radio reports 7.6V, which is fine. I cannot exclude that there are bugs for the other radios, however. Which model do you have?

**Comment by silseva** [comment]
Tested also on my RT3S compiling from the latest commit on master branch: battery voltage is 7.43V, radio reports 7.3V and battery level 25%.

Here you can find our nightlies too: https://files.openrtx.org/nightly/

**Comment by kmihaylov** [comment]
The battery indicator was fully black. Then it became fully green. This happened only once. I'll watch it.

I'll close the issue in day or two. Last time I checked the voltage was OK.

**Comment by silseva** [comment]
Hi @kmihaylov!
Can we considered the issue solved or it needs further investigation?

**Comment by sp5wwp** [comment]
I've got a similar (or maybe the same) problem with MD380. Seems like the code treats 7.10 as a higher value than 7.9.
![md380_voltage_bug](https://user-images.githubusercontent.com/44336093/173177079-60cdd0f2-8fb2-4b0a-b4eb-eb0c6552937f.jpeg)

**Comment by sp5wwp** [comment]
Most likely, the bug was in the integer part calculation. I have already opened a PR with a fix.
