### ISSUE TITLE
UI locks up when changing mode to M17

### ISSUE THREAD

**Issue by mathisschmieder** [OpenRTX/OpenRTX#74]
When running commit c0486fea7d8a0dbc53d52fcfd784f75b3fb28626 on my MD-UV380/RT3S, the UI locks up after changing the mode through the Macro-menu away from M17 and back to M17. Pressing PTT refreshes the screen and gets me back to the main screen, but other key inputs don't register. Furthermore, while the RF signal looks fine, the M17 signal does not demodulate anymore. Turning the radio off via the volume knob does not work. After taking out the battery, the radio is working fine and the transmitted M17 stream is decoded again.

**Comment by silseva** [comment]
Issue solved.
