### ISSUE TITLE
No M17 audio output after Tx

### ISSUE THREAD

**Issue by mathisschmieder** [OpenRTX/OpenRTX#76]
On my Module17 running commit ID 9eee1612a1a4cdf6278dceec1f0bda6e6e72aa26 I only get demodulated M17 audio out *before* I press PTT once. Afterwards, it looks like the audio stream is not being processed properly. The sync LED still lights up, but nothing gets put out through the speaker

**Comment by silseva** [comment]
Bug fixed

**Comment by mathisschmieder** [comment]
Not fixed for Module17, unfortunately!
