### ISSUE TITLE
Allow spaces in callsign for gateway control

### ISSUE THREAD

**Issue by jeffgus** [OpenRTX/OpenRTX#83]
I wasn't able to input a space for the Dst ID. This is required for m17gateway control (e.g. "M17-USA A"). I made this change and tested it with the latest build of M17Gateway:

```
diff --git a/openrtx/src/ui/ui.c b/openrtx/src/ui/ui.c
index 141f6f1..4eb4f85 100644
--- a/openrtx/src/ui/ui.c
+++ b/openrtx/src/ui/ui.c
@@ -203,7 +203,7 @@ const char *symbols_ITU_T_E161[] =
 
 const char *symbols_ITU_T_E161_callsign[] =
 {
-    "0",
+    "0 ",
     "1",
     "ABC2",
     "DEF3",

```

**Comment by silseva** [comment]
Hi!
Can you please open a pull-request for that?

**Comment by jeffgus** [comment]
Hi,
No problemo. I Created pull request #84 to fix this issue.

**Comment by silseva** [comment]
PR merged!
